### ISSUE TITLE
Never returns results

### ISSUE THREAD

**Issue by ScottESanDiego** [bexem/Fetch-Latest-File#1]
Using HA 2024.8.3 , I can't get this to return any attributes.

In "Developer Tools", calling this:

```
action: fetch_latest_file.fetch
data:
  FileName: conf
  Directory: /config
```

yields `No matching files found` even though clearly there is a `configuration.yaml` in that directory.

Before I fork this or dig into it, is there something obvious I'm missing?
